"""update scheduling and booking models

Revision ID: 0db15daf5ca2
Revises: 1b54f88c4cee
Create Date: 2026-02-12 14:38:40.391326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db15daf5ca2'
down_revision: Union[str, Sequence[str], None] = '1b54f88c4cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'REQUESTED', 'BOOKED', 'COMPLETED', name='availability_enum'), nullable=False),
    sa.Column('availabiliity_type', sa.Enum('SERVICE', 'BUSINESS', 'STAFF', name='availability_type_enum'), nullable=False),
    sa.CheckConstraint('end_time >= start_time', name='ck_valid_time_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'date', 'start_time', 'end_time', name='uq_record_date')
    )
    op.create_table('booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('availability_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('customization', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'CANCELLED', 'COMPLETE', name='booking_enum'), nullable=True),
    sa.Column('booking_type', sa.Enum('SERVICE', 'BUSINESS', 'STAFF', name='booking_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('availability')
    # ### end Alembic commands ###
