"""add booking and update relationships_2

Revision ID: 0fe1ebde16a5
Revises: e7a6c6df61f2
Create Date: 2026-02-05 15:41:05.652566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe1ebde16a5'
down_revision: Union[str, Sequence[str], None] = 'e7a6c6df61f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('availability_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('customization', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspiration_images', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'CANCELLED', 'COMPLETE', name='booking_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['business_availability.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('availability_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('customization', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspiration_images', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'CANCELLED', 'COMPLETE', name='booking_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['service_availability.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_booking')
    op.drop_table('business_booking')
    # ### end Alembic commands ###
