"""temp_remove_images

Revision ID: 1b54f88c4cee
Revises: 0fe1ebde16a5
Create Date: 2026-02-07 17:46:11.229979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b54f88c4cee'
down_revision: Union[str, Sequence[str], None] = '0fe1ebde16a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_booking', 'inspiration_images')
    op.drop_column('service_booking', 'inspiration_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_booking', sa.Column('inspiration_images', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_booking', sa.Column('inspiration_images', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
