"""update enums

Revision ID: 220c7fd194db
Revises: 75a17791a1d0
Create Date: 2026-02-20 20:10:22.306709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220c7fd194db'
down_revision: Union[str, Sequence[str], None] = '75a17791a1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE availability_type_enum ADD VALUE 'RESCHEDULED';")
    op.execute("ALTER TYPE availability_type_enum ADD VALUE 'EXPIRED';")
    op.execute("ALTER TYPE availability_type_enum ADD VALUE 'CANCELLED';")
    op.execute("ALTER TYPE availability_type_enum ADD VALUE 'UNAVAILABLE';")
    op.execute("ALTER TYPE booking_enum ADD VALUE 'RESCHEDULED';")
    op.execute("ALTER TYPE booking_enum ADD VALUE 'EXPIRED';")
    
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
