"""update availability status and booking availability enum

Revision ID: 75a17791a1d0
Revises: a3bd28dde83e
Create Date: 2026-02-20 20:05:50.585331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75a17791a1d0'
down_revision: Union[str, Sequence[str], None] = 'a3bd28dde83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_status', sa.Enum('AVAILABLE', 'REQUESTED', 'BOOKED', 'COMPLETED', 'UNAVAILABLE', 'CANCELLED', 'RESCHEDULED', 'EXPIRED', name='booking_enum'), nullable=True))
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', postgresql.ENUM('REQUESTED', 'ACCEPTED', 'CANCELLED', 'COMPLETE', name='booking_enum'), autoincrement=False, nullable=True))
    op.drop_column('booking', 'booking_status')
    # ### end Alembic commands ###
