"""adding scheduling_2_adjust mapping

Revision ID: 821d4fe20e48
Revises: b0daa54b7f2b
Create Date: 2026-02-02 15:19:30.425492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821d4fe20e48'
down_revision: Union[str, Sequence[str], None] = 'b0daa54b7f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
