"""update availability status enum

Revision ID: a3bd28dde83e
Revises: c4889a496d79
Create Date: 2026-02-20 19:55:38.006277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bd28dde83e'
down_revision: Union[str, Sequence[str], None] = 'c4889a496d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE availability_type_enum ADD VALUE 'RESCHEDULED';")
    op.execute("ALTER TYPE availability_type_enum ADD VALUE 'EXPIRED';")
    op.execute("ALTER TYPE availability_type_enum ADD VALUE 'CANCELLED';")
    op.execute("ALTER TYPE availability_type_enum ADD VALUE 'UNAVAILABLE';")

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
