"""adding scheduling_1

Revision ID: b0daa54b7f2b
Revises: ea0c0665fbbb
Create Date: 2026-02-02 15:07:39.839878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0daa54b7f2b'
down_revision: Union[str, Sequence[str], None] = 'ea0c0665fbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'REQUESTED', 'BOOKED', 'COMPLETED', name='availability_status_enum'), nullable=False),
    sa.CheckConstraint('end_time >= start_time', name='ck_business_valid_time_range'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'REQUESTED', 'BOOKED', 'COMPLETED', name='availability_status_enum'), nullable=False),
    sa.CheckConstraint('end_time >= start_time', name='ck_valid_time_range'),
    sa.ForeignKeyConstraint(['service_id'], ['business_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_availability')
    op.drop_table('business_availability')
    # ### end Alembic commands ###
