"""add unique constraints

Revision ID: b5386e110240
Revises: d367c5ad2f78
Create Date: 2026-02-03 17:26:59.453734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5386e110240'
down_revision: Union[str, Sequence[str], None] = 'd367c5ad2f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_business_date', 'business_availability', ['business_id', 'date', 'start_time', 'end_time'])
    op.create_unique_constraint('uq_service_date', 'service_availability', ['service_id', 'date', 'start_time', 'end_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_service_date', 'service_availability', type_='unique')
    op.drop_constraint('uq_business_date', 'business_availability', type_='unique')
    # ### end Alembic commands ###
