"""add timestamps to booking scheduling and off days

Revision ID: c4889a496d79
Revises: 8fc6bc834d8c
Create Date: 2026-02-15 18:10:46.440091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4889a496d79'
down_revision: Union[str, Sequence[str], None] = '8fc6bc834d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('availability', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('booking', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('booking', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('off_day', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('off_day', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('off_day', 'updated_at')
    op.drop_column('off_day', 'created_at')
    op.drop_column('booking', 'updated_at')
    op.drop_column('booking', 'created_at')
    op.drop_column('availability', 'updated_at')
    op.drop_column('availability', 'created_at')
    # ### end Alembic commands ###
